# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'HelloSayer']

# Cell
def say_hello(somebody):
    "Say hello to somebody"
    return f'Hello {somebody}!'

# Cell
class HelloSayer:
    "Say hello to `somebody` using `say_hello`"
    def __init__(self, somebody): self.somebody = somebody
    def say(self): return say_hello(self.somebody)
